name: get_gamer_data

on:
  schedule:
    - cron: '00 03 * * *'
  workflow_dispatch:

jobs:
  run_python_file:
    runs-on: windows-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r package.txt
    
    - name: execute python script
      run: python Python_crawler_for_gamer_ver2.py
