name: get_gamer_data

on:
  schedule:
    - cron: '00 19 * * *'
  workflow_dispatch: 
env: 
  PLAYER_SYSTEMCALL_GAMER_ID: ${{ secrets.PLAYER_SYSTEMCALL_GAMER_ID }}
jobs:
  run_python_file:
    runs-on: windows-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/package.txt
    - name: create json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google_sheets_API_key.json"
        json: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
    - name: execute python script
      run: |
        python Python_crawler_main_for_gamer_ver3github.py