name: test_env

on: 
  workflow_dispatch: 
  
jobs: 
  run_python_file: 
    runs-on: windows-latest
    steps: 
    - name: checkout repo content
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/package.txt
    
    - name: input the secret
      with:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: execute python script
      run: python envtest.py