name: test_env

on: 
  workflow_dispatch: 

jobs: 
  creat_json: 
    runs-on: windows-latest
    steps: 
    - name: checkout repo content
      uses: actions/checkout@v2
    
    - name: creat json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "cypress.json"
        json: ${{ secrets.TEST_API_KEY }}
           
    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/package.txt  
    
    - name: execute python script read and print
      run: python envtest.py
      
