name: test_env

on: 
  workflow_dispatch: 

jobs: 
  creat_json: 
    runs-on: windows-latest
    steps: 
    - name: checkout repo content
      uses: actions/checkout@v2
           
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/package.txt  
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google_sheets_API_key.json"
        json: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
    
    - name: execute python script read and print
      run: python envtest.py
      
